preload = ~/.config/hypr/wallpapers/wuffels.jpg
preload = ~/.config/hypr/wallpapers/Chunky_Abruf.jpeg
preload = ~/.config/hypr/wallpapers/Chunky_Schnee_1.jpg

wallpaper =  DP-2, ~/.config/hypr/wallpapers/Chunky_Schnee_1.jpg
wallpaper = HDMI-A-1, ~/.config/hypr/wallpapers/Chunky_Schnee_1.jpg

splash = false
